# Generated by Django 5.2.5 on 2025-09-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
